# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 20) do

  create_table "comments", :force => true do |t|
    t.column "body",         :text
    t.column "who",          :string
    t.column "when_created", :date
    t.column "accepted",     :integer
    t.column "news_id",      :integer
  end

  create_table "company_infos", :force => true do |t|
    t.column "company_name",        :string
    t.column "company_description", :text
    t.column "welcome_text",        :text
    t.column "web_icon",            :binary
    t.column "logo_image",          :binary
    t.column "banner_image",        :binary
    t.column "sidebar_image",       :binary
  end

  create_table "contacts", :force => true do |t|
    t.column "type_location", :integer
    t.column "description",   :string
    t.column "name",          :string
    t.column "adr_line1",     :string
    t.column "adr_line2",     :string
    t.column "city",          :string
    t.column "state",         :string
    t.column "postal_code",   :string
    t.column "phone",         :string
    t.column "cell",          :string
    t.column "office_phone",  :string
    t.column "fax",           :string
    t.column "email",         :string
    t.column "image_id",      :integer
  end

  create_table "db_files", :force => true do |t|
    t.column "name", :string
    t.column "body", :binary
  end

  add_index "db_files", ["name"], :name => "index_db_files_on_name", :unique => true

  create_table "disclosures", :force => true do |t|
    t.column "description", :text
  end

  create_table "images", :force => true do |t|
    t.column "content_type", :string
    t.column "large",        :binary, :limit => 10485760
    t.column "thumb",        :binary, :limit => 1048576
    t.column "caption",      :string
  end

  create_table "news", :force => true do |t|
    t.column "title",        :string
    t.column "when_created", :date
    t.column "who",          :string
    t.column "body",         :text
    t.column "image_id",     :integer, :default => 0
  end

  create_table "portfolio_entries", :force => true do |t|
    t.column "title",            :string
    t.column "description",      :text
    t.column "image_id",         :integer
    t.column "service_entry_id", :integer, :default => 0
    t.column "sort_order",       :integer, :default => 0
  end

  create_table "recommendations", :force => true do |t|
    t.column "title",    :string
    t.column "link",     :text
    t.column "image_id", :integer
  end

  create_table "service_entries", :force => true do |t|
    t.column "title",       :string
    t.column "description", :text
    t.column "image_id",    :integer
    t.column "disp_type",   :integer, :default => 0
    t.column "sort_order",  :integer, :default => 0
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"
  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"

  create_table "settings", :force => true do |t|
    t.column "name",  :string
    t.column "value", :string
  end

  add_index "settings", ["name"], :name => "index_settings_on_name", :unique => true

  create_table "testimonial_entries", :force => true do |t|
    t.column "customer_name", :string
    t.column "testimonial",   :text
  end

  create_table "users", :force => true do |t|
    t.column "name",            :string
    t.column "hashed_password", :string
    t.column "salt",            :string
  end

end
